### ISSUE TITLE
Erreur sur la fonction cron du plugin : Internal server error

### ISSUE THREAD

**Issue by TricloFL78** [PhilippeJ-code/viessmannIot#2]
Hi,
I've got the error message "Erreur sur la fonction cron du plugin : Internal server error" whatever the cron you are using. The lowest one we got is 5 minutes and not 2 minutes.
The other message concerning the cron is "Erreur sur la fonction cron du plugin : CONNECTION_TIMEOUT" or "Erreur sur la fonction cron du plugin : DEVICE_COMMUNICATION_ERROR".

I've got another message "Erreur sur la fonction cron du plugin : [MySQL] Error code : 22001 (1406). Data too long for column 'value' at row 1 : REPLACE INTO history SET cmd_id=:cmd_id, `datetime`=:datetime, value=:value". For this one, I don't think it's depending to the plugin viessmannIot, but to Jeedom.

Thank you in advance for your reply.

**Comment by PhilippeJ-code** [comment]
Hi,

**CONNECTION_TIMEOUT and DEVICE_COMMUNICATION_ERROR.** 

Ces erreurs proviennent de la connexion Internet avec le serveur Viessmann. J'ai aussi ces erreurs au moins une fois par jour. Ces erreurs sont sans conséquence sur le fonctionnement du plugin.

Google Translate : These errors originate from the Internet connection with the Viessmann server. I also have these errors at least once a day. These errors have no effect on the functioning of the plugin.

**MySQL Error**

You are probably historizing information that is too long for the database, 

Philippe

**Comment by TricloFL78** [comment]
Merci Philippe pour ton retour. En effet, tout semble fonctionner normalement. Quelle plus petit cron as-tu ?

Thank you Philippe for your return. Indeed, everything seems to be working normally. What smallest cron do you have?

**Comment by PhilippeJ-code** [comment]
I use the cron10
