### ISSUE TITLE
Graph for electricity

### ISSUE THREAD

**Issue by TricloFL78** [PhilippeJ-code/viessmannIot#3]
Hi Philippe,
We don't see bars for the electricity graph, but when you move the mouse on it you see well the value in the pop-up. 
For the gas graph, it works well.
François

**Comment by PhilippeJ-code** [comment]
Hi, it works well for me. Can you send me a print screen like this one.

Philippe

![image](https://user-images.githubusercontent.com/74320250/134350627-6cdafebd-1917-47e6-98cb-ea6eea89461c.png)

**Comment by TricloFL78** [comment]
Voici 👍 
![image](https://user-images.githubusercontent.com/61076919/134358235-50aad03a-824c-4bd6-a8f2-b44d2a0c9633.png)

**Comment by TricloFL78** [comment]
Pour le gaz :
![image](https://user-images.githubusercontent.com/61076919/134358669-e2533abc-8dc3-432e-b80f-9e896dc149cb.png)
![image](https://user-images.githubusercontent.com/61076919/134358737-a405243f-d3cf-44ab-99e5-94640c202277.png)

**Comment by PhilippeJ-code** [comment]
Bizarre, Ctrl F5 dans le navigateur n'arrange pas le problème ? Même si je suppose que vous avez déjà essayé

**Comment by TricloFL78** [comment]
J'ai le même résultat sur mes 2 Jeedom (test et prod). Lors de l'installation, j'avais bien les barres mais elles ont disparu lors d'une montée de version (màj). Pour info, je fais toutes les mises à jour.

**Comment by TricloFL78** [comment]
Est-ce que cela a un rapport avec les couleurs ? A-t-on la main pour les modifier ?

**Comment by PhilippeJ-code** [comment]
Les graduations sur les axes sont correctes donc les valeurs sont bien là d'autant plus qu'elles apparaissent bien dans le popup. Je vais vérifier mon code.

Pour la consommation, j'ai la même valeur tous les jours avec une précision à une seule décimale. Je vais faire un test avec 3 décimales pour voir.

**Comment by PhilippeJ-code** [comment]
Test avec 3 décimales ok, ce n'est donc pas ça. 

Pour les couleurs, on n'a pas la main pour les changer. Mais je vois que ta couleur de fond correspond à la couleur de la barre, tu veux bien essayer de la changer pour voir ce que ça donne ( on ne se sait jamais ).

**Comment by PhilippeJ-code** [comment]
Je viens de tester avec la couleur, ça ne change rien chez moi

**Comment by PhilippeJ-code** [comment]
Sur la consommation gaz du mois ( par exemple ) la consommation chauffage apparait ?

**Comment by TricloFL78** [comment]
Pour le gaz, ça marche pour jour, semaine, mois, année avec les mêmes couleurs. Je n'ai jamais eu de bleu pour les barres.
Je ne me souviens plus des couleurs que j'avais quand j'ai installé le pluging pour l'électricité, mais il me semble que ça ressemblait au rendu du gaz.

**Comment by TricloFL78** [comment]
C'est bien un problème de couleur : en changeant la couleur de fond j'obtiens l'image ci-dessous
![image](https://user-images.githubusercontent.com/61076919/134409402-95f715aa-3c39-456c-88f2-27f6dc3da14e.png)

**Comment by PhilippeJ-code** [comment]
Tu es en quelle version de Jeedom ?

**Comment by TricloFL78** [comment]
Version 4.1.25

**Comment by TricloFL78** [comment]
Est-ce que tu as le paramétrage pour le gaz et l'électricité pour les couleurs ?

**Comment by PhilippeJ-code** [comment]
J'ai forcé les valeurs, si tu veux bien faire la mise à jour et me dire ce que ça donne

**Comment by TricloFL78** [comment]
Génial, ça marche. Merci pour ta mise à jour.
![image](https://user-images.githubusercontent.com/61076919/134638752-458b9f9f-d5f7-46f8-aa20-78008f8c0be9.png)

**Comment by PhilippeJ-code** [comment]
Content que ça fonctionne
