### ISSUE TITLE
Remontée des informations dans le plugin

### ISSUE THREAD

**Issue by TricloFL78** [PhilippeJ-code/viessmannIot#4]
Bonjour Philippe,
Toutes les informations ne remontent plus dans le plugin depuis hier (températures, consommations, ...). Est-ce la cas chez toi aussi ?
Est-ce que Viessmann aurait encore changé des paramètres ?
François

**Comment by PhilippeJ-code** [comment]
Bonjour François,

Tout est correct chez moi, tu as la même chose dans Vicare ?

Philippe

**Comment by TricloFL78** [comment]
Vicare marche bien et mon script à partir du développement de Thetrueavatar remonte bien les informations (ce qui n'était pas le cas pour les consommations électriques avant la dernière version). 

Dans le plugin, depuis hier vers 15h, les valeurs suivantes ne remontent plus correctement 
![image](https://user-images.githubusercontent.com/61076919/135708192-fbdf1544-415d-4ba9-9357-d82df5f9f476.png)
Par exemple : 
la conso ecs d'aujourd'hui est de 1 kWh, il indique 7
la t° ext est de 12.4 °C, il indique 15.4 °C

Hier, j'ai utilisé le plugin pour ajuster la température de référence. est-ce que ça pourrait venir de là ?

**Comment by PhilippeJ-code** [comment]
Tu n'as pas une erreur dans le log ?

**Comment by TricloFL78** [comment]
Erreurs dans le log : 
"Erreur sur viessmannIot::salsa() : [MySQL] Error code : 22001 (1406). Data too long for column 'value' at row 1 : REPLACE INTO history SET cmd_id=:cmd_id, `datetime`=:datetime, value=:value"
J'ai la même erreur pour le script.

**Comment by PhilippeJ-code** [comment]
Encore un problème d'historisation, il ne faut historiser que les variables élémentaires comme une température ou une consigne mais pas des variables plus longues comme les consommations.
